### PR TITLE
Update gihyo logo

### PR DESCRIPTION
**Pull request by peacock0803sz**
SSIA
ref: <https://pyconjp.slack.com/files/USLACKBOT/F041LRJ83D3/re__pycon_jp_2022_______________________________________web__________________>

### CODE REVIEW

**Comment by peacock0803sz** [comment]
CleanShot 2022-09-09 at 14 00 36
Preview

**Comment by takanory** [comment]
ロゴのサイズ感をもうちょい揃えたい

**Comment by peacock0803sz** [comment]
image
50%にDownsizeしました

**Review by takanory — APPROVED** [review]
LGTM

**Pull request merged**
